In [135]:
import os
import pandas as pd

In [136]:
cities = pd.read_csv(os.path.join("data","List_of_European_cities_by_population_within_city_limits_1.csv")).drop(columns=['Date'])
df = pd.read_csv(os.path.join("data","matches.csv"))

In [137]:
cities['Official\npopulation'] = pd.to_numeric(cities['Official\npopulation'].apply(lambda x: x.replace(',','')))

In [138]:
cities

                City         Country  Official\npopulation  Ref.
0           Istanbul          Turkey              15655924   NaN
1             Moscow          Russia              13149803   NaN
2             London  United Kingdom               8866180   NaN
3   Saint Petersburg          Russia               5597763   NaN
4             Berlin         Germany               3755251   NaN
5             Madrid           Spain               3332035   NaN
6               Kyiv         Ukraine               2952301   NaN
7               Rome           Italy               2754719   NaN
8               Baku      Azerbaijan               2336600   NaN
9              Paris          France               2087577   NaN
10            Vienna         Austria               2006134   NaN
11             Minsk         Belarus               1992862   NaN
12           Hamburg         Germany               1892122   NaN
13            Warsaw          Poland               1861644   NaN
14         Bucharest         Romania               1739297   NaN
15          Belgrade          Serbia               1683229   NaN
16          Budapest         Hungary               1671004   NaN
17         Barcelona           Spain               1660122   NaN
18            Munich         Germany               1512491   NaN
19           Kharkiv         Ukraine               1421225   NaN
20            Prague  Czech Republic               1384732   NaN
21             Milan           Italy               1371850   NaN
22             Kazan          Russia               1318604   NaN
23             Sofia        Bulgaria               1286965   NaN
24           Tbilisi         Georgia               1241709   NaN
25   Nizhny Novgorod          Russia               1204985   NaN
26               Ufa          Russia               1163304   NaN
27            Samara          Russia               1158952   NaN
28        Birmingham  United Kingdom               1157163   NaN
29     Rostov-on-Don          Russia               1140487   NaN
30         Krasnodar          Russia               1138654   NaN
31           Yerevan         Armenia               1127000   NaN
32           Cologne         Germany               1084831   NaN
33          Voronezh          Russia               1046425   NaN
34              Perm          Russia               1026908   NaN
35         Volgograd          Russia               1018898   NaN
36             Odesa         Ukraine               1010537   NaN

In [139]:
df.loc[df['location'] == 'Bazaly', 'location'] = 'Bazaly, Ostrava'

In [140]:
df['competition'].drop_duplicates().to_list()

['UCL', 'ICFC', 'CWC', 'EL', 'Intertoto', 'UECL']

In [141]:
df = df[df['competition'].isin(['UCL','CWC','EL','UECL'])]

In [142]:
df['city'] = df['location'].apply(lambda x: str(x).split(',')[-1].strip())

In [143]:
def join_dates(row):
    if row['date'] != None:
        return row['date']
    else:
        return row['estimatedDate']

In [144]:
df['date'] = df.apply(lambda row: join_dates(row), axis = 1)
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [145]:
soccer_cities = df.groupby('city')['date'].max()
soccer_cities = pd.DataFrame(soccer_cities).reset_index().rename(columns={'city': 'City'})

In [146]:
cities

                City         Country  Official\npopulation  Ref.
0           Istanbul          Turkey              15655924   NaN
1             Moscow          Russia              13149803   NaN
2             London  United Kingdom               8866180   NaN
3   Saint Petersburg          Russia               5597763   NaN
4             Berlin         Germany               3755251   NaN
5             Madrid           Spain               3332035   NaN
6               Kyiv         Ukraine               2952301   NaN
7               Rome           Italy               2754719   NaN
8               Baku      Azerbaijan               2336600   NaN
9              Paris          France               2087577   NaN
10            Vienna         Austria               2006134   NaN
11             Minsk         Belarus               1992862   NaN
12           Hamburg         Germany               1892122   NaN
13            Warsaw          Poland               1861644   NaN
14         Bucharest         Romania               1739297   NaN
15          Belgrade          Serbia               1683229   NaN
16          Budapest         Hungary               1671004   NaN
17         Barcelona           Spain               1660122   NaN
18            Munich         Germany               1512491   NaN
19           Kharkiv         Ukraine               1421225   NaN
20            Prague  Czech Republic               1384732   NaN
21             Milan           Italy               1371850   NaN
22             Kazan          Russia               1318604   NaN
23             Sofia        Bulgaria               1286965   NaN
24           Tbilisi         Georgia               1241709   NaN
25   Nizhny Novgorod          Russia               1204985   NaN
26               Ufa          Russia               1163304   NaN
27            Samara          Russia               1158952   NaN
28        Birmingham  United Kingdom               1157163   NaN
29     Rostov-on-Don          Russia               1140487   NaN
30         Krasnodar          Russia               1138654   NaN
31           Yerevan         Armenia               1127000   NaN
32           Cologne         Germany               1084831   NaN
33          Voronezh          Russia               1046425   NaN
34              Perm          Russia               1026908   NaN
35         Volgograd          Russia               1018898   NaN
36             Odesa         Ukraine               1010537   NaN

In [147]:
merg = cities.merge(soccer_cities, on='City', how='outer')

In [148]:
merg = merg[merg['Official\npopulation'].notnull()]

In [149]:
merg[merg['date'].isnull()].sort_values(by='Official\npopulation',ascending=False)

                City Country  Official\npopulation  Ref. date
546  Nizhny Novgorod  Russia             1204985.0   NaN  NaT
857         Voronezh  Russia             1046425.0   NaN  NaT

In [150]:
df[df['date'] == '1997-08-26']

,competition,date,score,homeTeam,homeTeamCountry,homeTeamUrl,awayTeam,awayTeamCountry,awayTeamUrl,location,phase,attendance,estimatedDate,competitonOriginal,season,city
9562,EL,1997-08-26,3-2,AGF Aarhus,Denmark,Aarhus_Gymnastik_Forening,Újpest,Hungary,%C3%9Ajpest_FC,Aarhus,second qualifying round,NaN,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Aarhus
9563,EL,1997-08-26,2-0,Boby Brno,Czech Republic,FC_Zbrojovka_Brno,Rapid Wien,Austria,SK_Rapid_Wien,Brno,second qualifying round,NaN,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Brno
9564,EL,1997-08-26,2-0,Brann,Norway,SK_Brann,Grasshoppers,Switzerland,Grasshopper_Club_Z%C3%BCrich,Bergen,second qualifying round,NaN,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Bergen
9565,EL,1997-08-26,6-3,Celtic,Scotland,Celtic_F.C.,Tirol Innsbruck,Austria,FC_Tirol_Innsbruck,Glasgow,second qualifying round,46907.0,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Glasgow
9566,EL,1997-08-26,3-0,Club Brugge,Belgium,Club_Brugge_K.V.,Gorica,Slovenia,ND_Gorica,Bruges,second qualifying round,NaN,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Bruges
9567,EL,1997-08-26,1-4,Dnipro Dnipropetrovsk,Ukraine,FC_Dnipro_Dnipropetrovsk,Alania Vladikavkaz,Russia,FC_Alania_Vladikavkaz,"Meteor, Dnipropetrovsk",second qualifying round,8.0,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Dnipropetrovsk
9568,EL,1997-08-26,1-1,Dundee United,Scotland,Dundee_United_F.C.,Trabzonspor,Turkey,Trabzonspor,Dundee,second qualifying round,NaN,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Dundee
9569,EL,1997-08-26,3-0,Excelsior Mouscron,Belgium,R.E._Mouscron,Apollon Limassol,Cyprus,Apollon_Limassol,"Stadium Nord de Villeneuve d'Ascq, Villeneuve-...",second qualifying round,NaN,NaN,1997%E2%80%9398 UEFA Cup,1997-98,France
9570,EL,1997-08-26,0-1,Ferencváros,Hungary,Ferencv%C3%A1rosi_TC,Helsingborg,Sweden,Helsingborgs_IF,Budapest,second qualifying round,NaN,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Budapest
9571,EL,1997-08-26,1-0,Hapoel Petah Tikva,Israel,Hapoel_Petah_Tikva_F.C.,Vejle,Denmark,Vejle_Boldklub,Petah Tikva,second qualifying round,NaN,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Petah Tikva
9572,EL,1997-08-26,1-0,Lillestrøm,Norway,Lillestr%C3%B8m_SK,Dinamo Minsk,Belarus,FC_Dinamo_Minsk,"Åråsen Stadion, Lillestrøm",second qualifying round,1906.0,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Lillestrøm
9573,EL,1997-08-26,0-2,Malmö,Sweden,Malm%C3%B6_FF,Hajduk Split,Croatia,HNK_Hajduk_Split,"Malmö Stadion, Malmö",second qualifying round,8000.0,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Malmö
9574,EL,1997-08-26,3-1,OFI,Greece,OFI_Crete_F.C.,KR Reykjavík,Iceland,Knattspyrnuf%C3%A9lag_Reykjav%C3%ADkur,Heraklion,second qualifying round,NaN,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Heraklion
9575,EL,1997-08-26,3-4,Odra Wodzisław,Poland,Odra_Wodzis%C5%82aw,Rotor Volgograd,Russia,FC_Rotor_Volgograd,Wodzislaw,second qualifying round,NaN,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Wodzislaw
9576,EL,1997-08-26,0-1,Spartak Trnava,Slovakia,FC_Spartak_Trnava,PAOK,Greece,P.A.O.K._F.C.,"Anton Malatinský Stadium, Trnava",second qualifying round,15850.0,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Trnava
9577,EL,1997-08-26,2-1,Viking,Norway,Viking_FK,Neuchâtel Xamax,Switzerland,Neuch%C3%A2tel_Xamax,"Stavanger Stadion, Stavanger",second qualifying round,1877.0,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Stavanger
9578,EL,1997-08-26,0-2,Vorskla Poltava,Ukraine,FC_Vorskla_Poltava,Anderlecht,Belgium,R.S.C._Anderlecht,"Vorskla Stadium, Poltava",second qualifying round,19000.0,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Poltava
9579,EL,1997-08-26,0-0,Örebro,Sweden,%C3%96rebro_SK,FK Jablonec 97,Czech Republic,FK_Baumit_Jablonec,Örebro,second qualifying round,NaN,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Örebro

In [156]:
df[df['homeTeam'].str.contains('Gork')]

Empty DataFrame
Columns: [competition, date, score, homeTeam, homeTeamCountry, homeTeamUrl, awayTeam, awayTeamCountry, awayTeamUrl, location, phase, attendance, estimatedDate, competitonOriginal, season, city]
Index: []

In [151]:
merg[merg['Official\npopulation'] > 1000000].sort_values(by='date').head(30)

                 City         Country  Official\npopulation  Ref.       date
855         Volgograd          Russia             1018898.0   NaN 1998-08-25
680            Samara          Russia             1158952.0   NaN 2009-08-06
601              Perm          Russia             1026908.0   NaN 2009-08-27
301           Hamburg         Germany             1892122.0   NaN 2010-05-12
806               Ufa          Russia             1163304.0   NaN 2018-08-30
567             Odesa         Ukraine             1010537.0   NaN 2019-08-08
664     Rostov-on-Don          Russia             1140487.0   NaN 2020-09-24
490             Minsk         Belarus             1992862.0   NaN 2020-10-01
386         Krasnodar          Russia             1138654.0   NaN 2021-02-18
353             Kazan          Russia             1318604.0   NaN 2021-08-12
359           Kharkiv         Ukraine             1421225.0   NaN 2021-08-25
509            Moscow          Russia            13149803.0   NaN 2021-11-25
396              Kyiv         Ukraine             2952301.0   NaN 2021-12-07
674  Saint Petersburg          Russia             5597763.0   NaN 2022-02-17
162           Cologne         Germany             1084831.0   NaN 2022-11-03
86             Berlin         Germany             3755251.0   NaN 2023-12-12
489             Milan           Italy             1371850.0   NaN 2024-04-11
66          Barcelona           Spain             1660122.0   NaN 2024-04-16
516            Munich         Germany             1512491.0   NaN 2024-04-30
661              Rome           Italy             2754719.0   NaN 2024-05-02
94         Birmingham  United Kingdom             1157163.0   NaN 2024-05-02
594             Paris          France             2087577.0   NaN 2024-05-07
461            Madrid           Spain             3332035.0   NaN 2024-05-08
444            London  United Kingdom             8866180.0   NaN 2024-06-01
129         Bucharest         Romania             1739297.0   NaN 2024-07-23
131          Budapest         Hungary             1671004.0   NaN 2024-07-23
866            Warsaw          Poland             1861644.0   NaN 2024-07-25
766           Tbilisi         Georgia             1241709.0   NaN 2024-07-25
725             Sofia        Bulgaria             1286965.0   NaN 2024-07-25
327          Istanbul          Turkey            15655924.0   NaN 2024-07-30

In [152]:
df[df['city'] == 'Birmingham']

,competition,date,score,homeTeam,homeTeamCountry,homeTeamUrl,awayTeam,awayTeamCountry,awayTeamUrl,location,phase,attendance,estimatedDate,competitonOriginal,season,city
3182,EL,1975-10-01,0-1,Aston Villa,England,Aston_Villa_F.C.,Royal Antwerp,Belgium,Royal_Antwerp_F.C.,"Villa Park, Birmingham",first round,31513.000,NaN,1975%E2%80%9376 UEFA Cup,1975-76,Birmingham
3648,EL,1977-09-14,4-0,Aston Villa,England,Aston_Villa_F.C.,Fenerbahçe,Turkey,Fenerbah%C3%A7e_S.K._(football),"Villa Park, Birmingham",first round,30351.000,NaN,1977%E2%80%9378 UEFA Cup,1977-78,Birmingham
3711,EL,1977-10-19,2-0,Aston Villa,England,Aston_Villa_F.C.,Górnik Zabrze,Poland,G%C3%B3rnik_Zabrze,"Villa Park, Birmingham",second round,34138.000,NaN,1977%E2%80%9378 UEFA Cup,1977-78,Birmingham
3741,EL,1977-11-23,2-0,Aston Villa,England,Aston_Villa_F.C.,Athletic Bilbao,Spain,Athletic_Bilbao,"Villa Park, Birmingham",third round,32973.000,NaN,1977%E2%80%9378 UEFA Cup,1977-78,Birmingham
3757,EL,1978-03-01,2-2,Aston Villa,England,Aston_Villa_F.C.,Barcelona,Spain,FC_Barcelona,"Villa Park, Birmingham",quarter-finals,46619.000,NaN,1977%E2%80%9378 UEFA Cup,1977-78,Birmingham
4018,EL,1979-03-21,1-1,West Bromwich Albion,England,West_Bromwich_Albion_F.C.,Red Star Belgrade,Socialist Federal Republic of Yugoslavia,Red_Star_Belgrade,"The Hawthorns, Birmingham",quarter-finals,31110.000,NaN,1978%E2%80%9379 UEFA Cup,1978-79,Birmingham
4766,UCL,1981-09-16,5-0,Aston Villa,England,Aston_Villa_F.C.,Valur,Iceland,Valur_(men%27s_football),"Villa Park, Birmingham",first round,20481.000,NaN,1981%E2%80%9382 European Cup,1981-82,Birmingham
4806,UCL,1981-11-04,0-1,Aston Villa,England,Aston_Villa_F.C.,BFC Dynamo,East Germany,Berliner_FC_Dynamo,"Villa Park, Birmingham",second round,28175.000,NaN,1981%E2%80%9382 European Cup,1981-82,Birmingham
4818,UCL,1982-03-17,2-0,Aston Villa,England,Aston_Villa_F.C.,Dynamo Kyiv,Soviet Union,FC_Dynamo_Kyiv,"Villa Park, Birmingham",quarter-finals,38579.000,NaN,1981%E2%80%9382 European Cup,1981-82,Birmingham
4822,UCL,1982-04-07,1-0,Aston Villa,England,Aston_Villa_F.C.,Anderlecht,Belgium,R.S.C._Anderlecht,"Villa Park, Birmingham",semi-finals,38593.000,NaN,1981%E2%80%9382 European Cup,1981-82,Birmingham
5023,UCL,1982-09-15,3-1,Aston Villa,England,Aston_Villa_F.C.,Beşiktaş,Turkey,Be%C5%9Fikta%C5%9F_J.K.,"Villa Park, Birmingham",first round,150.000,NaN,1982%E2%80%9383 European Cup,1982-83,Birmingham
5060,UCL,1982-11-03,4-2,Aston Villa,England,Aston_Villa_F.C.,Dinamo București,Romania,FC_Dinamo_Bucure%C8%99ti,"Villa Park, Birmingham",second round,22244.000,NaN,1982%E2%80%9383 European Cup,1982-83,Birmingham
5066,UCL,1983-03-02,1-2,Aston Villa,England,Aston_Villa_F.C.,Juventus,Italy,Juventus_FC,"Villa Park, Birmingham",quarter-finals,45531.000,NaN,1982%E2%80%9383 European Cup,1982-83,Birmingham
5179,EL,1983-09-28,5-0,Aston Villa,England,Aston_Villa_F.C.,Vitória S.C.,Portugal,Vit%C3%B3ria_S.C.,"Villa Park, Birmingham",first round,23732.000,NaN,1983%E2%80%9384 UEFA Cup,1983-84,Birmingham
5222,EL,1983-11-02,1-2,Aston Villa,England,Aston_Villa_F.C.,Spartak Moscow,Soviet Union,FC_Spartak_Moscow,"Villa Park, Birmingham",second round,29511.000,NaN,1983%E2%80%9384 UEFA Cup,1983-84,Birmingham
6887,EL,1990-09-19,3-1,Aston Villa,England,Aston_Villa_F.C.,Baník Ostrava,Czechoslovakia,FC_Ban%C3%ADk_Ostrava,"Villa Park, Birmingham",first round,27317.000,NaN,1990%E2%80%9391 UEFA Cup,1990-91,Birmingham
6943,EL,1990-10-24,2-0,Aston Villa,England,Aston_Villa_F.C.,Internazionale,Italy,Inter_Milan,"Villa Park, Birmingham",second round,36461.000,NaN,1990%E2%80%9391 UEFA Cup,1990-91,Birmingham
7734,EL,1993-09-29,2-1,Aston Villa,England,Aston_Villa_F.C.,Slovan Bratislava,Slovakia,%C5%A0K_Slovan_Bratislava,"Villa Park, Birmingham",first round,24461.000,NaN,1993%E2%80%9394 UEFA Cup,1993-94,Birmingham
7772,EL,1993-11-03,0-1,Aston Villa,England,Aston_Villa_F.C.,Deportivo La Coruña,Spain,Deportivo_de_La_Coru%C3%B1a,"Villa Park, Birmingham",second round,26737.000,NaN,1993%E2%80%9394 UEFA Cup,1993-94,Birmingham
8109,EL,1994-09-29,1-0,Aston Villa,England,Aston_Villa_F.C.,Internazionale,Italy,Inter_Milan,"Villa Park, Birmingham",first round,30533.000,NaN,1994%E2%80%9395 UEFA Cup,1994-95,Birmingham
8126,EL,1994-11-01,2-1,Aston Villa,England,Aston_Villa_F.C.,Trabzonspor,Turkey,Trabzonspor,"Villa Park, Birmingham",second round,23858.000,NaN,1994%E2%80%9395 UEFA Cup,1994-95,Birmingham
9076,EL,1996-09-10,1-1,Aston Villa,England,Aston_Villa_F.C.,Helsingborg,Sweden,Helsingborgs_IF,"Villa Park, Birmingham",first round,25818.000,NaN,1996%E2%80%9397 UEFA Cup,1996-97,Birmingham
9618,EL,1997-09-30,1-0,Aston Villa,England,Aston_Villa_F.C.,Bordeaux,France,FC_Girondins_de_Bordeaux,Birmingham,first round,33072.000,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Birmingham
9662,EL,1997-11-04,2-1,Aston Villa,England,Aston_Villa_F.C.,Athletic Bilbao,Spain,Athletic_Bilbao,"Villa Park, Birmingham",second round,35915.000,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Birmingham
9684,EL,1997-12-09,2-0,Aston Villa,England,Aston_Villa_F.C.,Steaua București,Romania,FC_Steaua_Bucure%C8%99ti,"Villa Park, Birmingham",third round,35.102,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Birmingham
9696,EL,1998-03-17,2-1,Aston Villa,England,Aston_Villa_F.C.,Atlético Madrid,Spain,Atl%C3%A9tico_Madrid,"Villa Park, Birmingham",quarter-finals,39163.000,NaN,1997%E2%80%9398 UEFA Cup,1997-98,Birmingham
10059,CWC,1999-05-19,2-1,Lazio,Italy,S.S._Lazio,Mallorca,Spain,RCD_Mallorca,"Villa Park, Birmingham",final,33021.000,NaN,1998%E2%80%9399 UEFA Cup Winners%27 Cup,1998-99,Birmingham
10141,EL,1998-09-15,3-2,Aston Villa,England,Aston_Villa_F.C.,Strømsgodset,Norway,Str%C3%B8msgodset_Toppfotball,"Villa Park, Birmingham",first round,28893.000,NaN,1998%E2%80%9399 UEFA Cup,1998-99,Birmingham
10220,EL,1998-11-03,1-3,Aston Villa,England,Aston_Villa_F.C.,Celta Vigo,Spain,Celta_de_Vigo,"Villa Park, Birmingham",second round,29910.000,NaN,1998%E2%80%9399 UEFA Cup,1998-99,Birmingham
11888,EL,2001-09-20,2-3,Aston Villa,England,Aston_Villa_F.C.,Varteks,Croatia,NK_Vara%C5%BEdin_(1931%E2%80%932015),"Villa Park, Birmingham",first round,27132.000,NaN,2001%E2%80%9302 UEFA Cup,2001-02,Birmingham
16320,EL,2008-08-28,1-1,Aston Villa,England,Aston_Villa,FH,Iceland,Fimleikaf%C3%A9lag_Hafnarfjar%C3%B0ar,"Villa Park, Birmingham",second qualifying round,25415.000,NaN,2008%E2%80%9309 UEFA Cup qualifying rounds,2008-09,Birmingham
16394,EL,2008-10-02,1-1,Aston Villa,England,Aston_Villa_F.C.,Litex Lovech,Bulgaria,PFC_Litex_Lovech,"Villa Park, Birmingham",first round,27225.000,NaN,2008%E2%80%9309 UEFA Cup first round,2008-09,Birmingham
16430,EL,2008-10-23,2-1,Aston Villa,England,Aston_Villa_F.C.,Ajax,Netherlands,AFC_Ajax,"Villa Park, Birmingham",group stage,36657.000,NaN,2008%E2%80%9309 UEFA Cup group stage,2008-09,Birmingham
16486,EL,2008-12-04,1-2,Aston Villa,England,Aston_Villa_F.C.,Žilina,Slovakia,M%C5%A0K_%C5%BDilina,"Villa Park, Birmingham",group stage,28797.000,NaN,2008%E2%80%9309 UEFA Cup group stage,2008-09,Birmingham
16511,EL,2009-02-18,1-1,Aston Villa,England,Aston_Villa_F.C.,CSKA Moscow,Russia,PFC_CSKA_Moscow,"Villa Park, Birmingham",round of 32,38038.000,NaN,2008%E2%80%9309 UEFA Cup knockout stage,2008-09,Birmingham
17022,EL,2009-08-27,2-1,Aston Villa,England,Aston_Villa_F.C.,Rapid Wien,Austria,SK_Rapid_Wien,"Villa Park, Birmingham",play-off round,22563.000,NaN,2009%E2%80%9310 UEFA Europa League qualifying ...,2009-10,Birmingham
17718,EL,2010-08-26,2-3,Aston Villa,England,Aston_Villa_F.C.,Rapid Wien,Austria,SK_Rapid_Wien,"Villa Park, Birmingham",play-off round,29980.000,NaN,2010%E2%80%9311 UEFA Europa League play-off round,2010-11,Birmingham
18411,EL,2011-08-25,3-0,Birmingham City,England,Birmingham_City_F.C.,Nacional,Portugal,C.D._Nacional,"St Andrew's, Birmingham",play-off round,27698.000,NaN,2011%E2%80%9312 UEFA Europa League play-off round,2011-12,Birmingham
18449,EL,2011-09-15,1-3,Birmingham City,England,Birmingham_City_F.C.,Braga,Portugal,S.C._Braga,"St Andrew's, Birmingham",group stage,21747.000,NaN,2011%E2%80%9312 UEFA Europa League group stage,2011-12,Birmingham
18521,EL,2011-11-03,2-2,Birmingham City,England,Birmingham_City_F.C.,Club Brugge,Belgium,Club_Brugge_K.V.,"St Andrew's, Birmingham",group stage,26849.000,NaN,2011%E2%80%9312 UEFA Europa League group stage,2011-12,Birmingham
18579,EL,2011-12-15,1-0,Birmingham City,England,Birmingham_City_F.C.,Maribor,Slovenia,NK_Maribor,"St Andrew's, Birmingham",group stage,21436.000,NaN,2011%E2%80%9312 UEFA Europa League group stage,2011-12,Birmingham
27334,UECL,2023-08-31,3-0,Aston Villa,England,NaN,Hibernian,Scotland,NaN,"Villa Park, Birmingham",play-off round,39467.000,NaN,2023%E2%80%9324 UEFA Europa Conference League ...,2023-24,Birmingham
27373,UECL,2023-10-05,1-0,Aston Villa,England,Aston_Villa_F.C.,Zrinjski Mostar,Bosnia and Herzegovina,H%C5%A0K_Zrinjski_Mostar,"Villa Park, Birmingham",group stage,37327.000,NaN,2023%E2%80%9324 UEFA Europa Conference League ...,2023-24,Birmingham
27402,UECL,2023-11-09,2-1,Aston Villa,England,Aston_Villa_F.C.,AZ,Netherlands,AZ_Alkmaar,"Villa Park, Birmingham",group stage,35156.000,NaN,2023%E2%80%9324 UEFA Europa Conference League ...,2023-24,Birmingham
27420,UECL,2023-11-30,2-1,Aston Villa,England,Aston_Villa_F.C.,Legia Warsaw,Poland,Legia_Warsaw,"Villa Park, Birmingham",group stage,37866.000,NaN,2023%E2%80%9324 UEFA Europa Conference League ...,2023-24,Birmingham
27474,UECL,2024-03-14,4-0,Aston Villa,England,NaN,Ajax,Netherlands,NaN,"Villa Park, Birmingham",round of 16,37916.000,NaN,2023%E2%80%9324 UEFA Europa Conference League ...,2023-24,Birmingham
27482,UECL,2024-04-11,2-1,Aston Villa,England,Aston_Villa_F.C.,Lille,France,Lille_OSC,"Villa Park, Birmingham",quarter-finals,37220.000,NaN,2023%E2%80%9324 UEFA Europa Conference League ...,2023-24,Birmingham
27490,UECL,2024-05-02,2-4,Aston Villa,England,Aston_Villa_F.C.,Olympiacos,Greece,Olympiacos_F.C.,"Villa Park, Birmingham",semi-finals,41220.000,NaN,2023%E2%80%9324 UEFA Europa Conference League ...,2023-24,Birmingham